name: Post Push Repository Check

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deployment handled by local pre-push hook
        run: echo "Deployment is handled by the local AWS pre-push hook. No action needed here."
